// Curated list of undergraduate / tecnólogo courses common in Brazil.
// Source: distilled from INEP/MEC course taxonomies + common variants.
// `popular: true` surfaces the course at the top of the autocomplete.
// Matching (in AutocompleteInput) is case- and accent-insensitive and the
// onboarding accepts any free-typed value, so this list is a convenience —
// not an allow-list.

export const cursos = [
  // ── Engenharias ─────────────────────────────────────────────
  { nome: 'Engenharia Civil', area: 'Engenharias', popular: true },
  { nome: 'Engenharia de Produção', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Mecânica', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Elétrica', area: 'Engenharias', popular: true },
  { nome: 'Engenharia de Computação', area: 'Engenharias', popular: true },
  { nome: 'Engenharia de Software', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Química', area: 'Engenharias', popular: true },
  { nome: 'Engenharia de Controle e Automação', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Ambiental', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Mecatrônica', area: 'Engenharias', popular: true },
  { nome: 'Engenharia Eletrônica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Telecomunicações', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Aeronáutica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Aeroespacial', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Naval', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Petróleo', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Materiais', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Metalúrgica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Minas', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Alimentos', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Biomédica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Bioquímica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Florestal', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Agrícola', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Agronômica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Sanitária', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Sanitária e Ambiental', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Cartográfica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Agrimensura', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Têxtil', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Física', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Energia', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Transportes', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Pesca', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Hídrica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Bioprocessos', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Manufatura', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Acústica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Segurança do Trabalho', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Inovação', area: 'Engenharias', popular: false },

  // ── Ciências da Saúde ───────────────────────────────────────
  { nome: 'Medicina', area: 'Ciências da Saúde', popular: true },
  { nome: 'Enfermagem', area: 'Ciências da Saúde', popular: true },
  { nome: 'Fisioterapia', area: 'Ciências da Saúde', popular: true },
  { nome: 'Odontologia', area: 'Ciências da Saúde', popular: true },
  { nome: 'Farmácia', area: 'Ciências da Saúde', popular: true },
  { nome: 'Nutrição', area: 'Ciências da Saúde', popular: true },
  { nome: 'Biomedicina', area: 'Ciências da Saúde', popular: true },
  { nome: 'Psicologia', area: 'Ciências da Saúde', popular: true },
  { nome: 'Educação Física', area: 'Ciências da Saúde', popular: true },
  { nome: 'Medicina Veterinária', area: 'Ciências da Saúde', popular: true },
  { nome: 'Fonoaudiologia', area: 'Ciências da Saúde', popular: false },
  { nome: 'Terapia Ocupacional', area: 'Ciências da Saúde', popular: false },
  { nome: 'Saúde Coletiva', area: 'Ciências da Saúde', popular: false },
  { nome: 'Gerontologia', area: 'Ciências da Saúde', popular: false },
  { nome: 'Obstetrícia', area: 'Ciências da Saúde', popular: false },
  { nome: 'Optometria', area: 'Ciências da Saúde', popular: false },
  { nome: 'Naturologia', area: 'Ciências da Saúde', popular: false },
  { nome: 'Quiropraxia', area: 'Ciências da Saúde', popular: false },
  { nome: 'Podologia', area: 'Ciências da Saúde', popular: false },

  // ── Ciências Sociais Aplicadas ──────────────────────────────
  { nome: 'Administração', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Direito', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Ciências Contábeis', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Ciências Econômicas', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Relações Internacionais', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Marketing', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Comércio Exterior', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Administração Pública', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Ciências Atuariais', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Serviço Social', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Turismo', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Hotelaria', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Secretariado Executivo', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Biblioteconomia', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Arquivologia', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Museologia', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão de Recursos Humanos', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Recursos Humanos', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Gestão de Pessoas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Comercial', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Gestão de Negócios', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Financeira', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Pública', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão da Qualidade', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Hospitalar', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Ambiental', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão do Agronegócio', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão de Cooperativas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Logística', area: 'Ciências Sociais Aplicadas', popular: true },
  { nome: 'Eventos', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Negócios Imobiliários', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Empreendedorismo', area: 'Ciências Sociais Aplicadas', popular: false },

  // ── Comunicação e Artes ─────────────────────────────────────
  { nome: 'Publicidade e Propaganda', area: 'Comunicação e Artes', popular: true },
  { nome: 'Jornalismo', area: 'Comunicação e Artes', popular: true },
  { nome: 'Comunicação Social', area: 'Comunicação e Artes', popular: true },
  { nome: 'Relações Públicas', area: 'Comunicação e Artes', popular: false },
  { nome: 'Rádio, TV e Internet', area: 'Comunicação e Artes', popular: false },
  { nome: 'Cinema e Audiovisual', area: 'Comunicação e Artes', popular: true },
  { nome: 'Produção Audiovisual', area: 'Comunicação e Artes', popular: false },
  { nome: 'Produção Cultural', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design', area: 'Comunicação e Artes', popular: true },
  { nome: 'Design Gráfico', area: 'Comunicação e Artes', popular: true },
  { nome: 'Design de Produto', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design de Interiores', area: 'Comunicação e Artes', popular: true },
  { nome: 'Design de Moda', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design Digital', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design de Games', area: 'Comunicação e Artes', popular: false },
  { nome: 'Arquitetura e Urbanismo', area: 'Comunicação e Artes', popular: true },
  { nome: 'Artes Visuais', area: 'Comunicação e Artes', popular: false },
  { nome: 'Artes Cênicas', area: 'Comunicação e Artes', popular: false },
  { nome: 'Teatro', area: 'Comunicação e Artes', popular: false },
  { nome: 'Dança', area: 'Comunicação e Artes', popular: false },
  { nome: 'Música', area: 'Comunicação e Artes', popular: true },
  { nome: 'Composição', area: 'Comunicação e Artes', popular: false },
  { nome: 'Regência', area: 'Comunicação e Artes', popular: false },
  { nome: 'Canto', area: 'Comunicação e Artes', popular: false },
  { nome: 'Fotografia', area: 'Comunicação e Artes', popular: false },
  { nome: 'Moda', area: 'Comunicação e Artes', popular: false },
  { nome: 'Estilismo', area: 'Comunicação e Artes', popular: false },
  { nome: 'Conservação e Restauro', area: 'Comunicação e Artes', popular: false },

  // ── Computação e TI ─────────────────────────────────────────
  { nome: 'Ciência da Computação', area: 'Computação e TI', popular: true },
  { nome: 'Sistemas de Informação', area: 'Computação e TI', popular: true },
  { nome: 'Análise e Desenvolvimento de Sistemas', area: 'Computação e TI', popular: true },
  { nome: 'Ciência de Dados', area: 'Computação e TI', popular: true },
  { nome: 'Engenharia de Dados', area: 'Computação e TI', popular: true },
  { nome: 'Inteligência Artificial', area: 'Computação e TI', popular: true },
  { nome: 'Cibersegurança', area: 'Computação e TI', popular: true },
  { nome: 'Segurança da Informação', area: 'Computação e TI', popular: false },
  { nome: 'Defesa Cibernética', area: 'Computação e TI', popular: false },
  { nome: 'Jogos Digitais', area: 'Computação e TI', popular: false },
  { nome: 'Redes de Computadores', area: 'Computação e TI', popular: false },
  { nome: 'Banco de Dados', area: 'Computação e TI', popular: false },
  { nome: 'Sistemas para Internet', area: 'Computação e TI', popular: false },
  { nome: 'Sistemas Embarcados', area: 'Computação e TI', popular: false },
  { nome: 'Internet das Coisas', area: 'Computação e TI', popular: false },
  { nome: 'Computação em Nuvem', area: 'Computação e TI', popular: false },
  { nome: 'Gestão da Tecnologia da Informação', area: 'Computação e TI', popular: false },

  // ── Ciências Exatas e da Terra ──────────────────────────────
  { nome: 'Matemática', area: 'Ciências Exatas e da Terra', popular: true },
  { nome: 'Física', area: 'Ciências Exatas e da Terra', popular: true },
  { nome: 'Química', area: 'Ciências Exatas e da Terra', popular: true },
  { nome: 'Estatística', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Matemática Aplicada', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Matemática Aplicada e Computacional', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Astronomia', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Geologia', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Geofísica', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Oceanografia', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Meteorologia', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Física Médica', area: 'Ciências Exatas e da Terra', popular: false },
  { nome: 'Nanotecnologia', area: 'Ciências Exatas e da Terra', popular: false },

  // ── Ciências Biológicas ─────────────────────────────────────
  { nome: 'Ciências Biológicas', area: 'Ciências Biológicas', popular: true },
  { nome: 'Biologia', area: 'Ciências Biológicas', popular: true },
  { nome: 'Biotecnologia', area: 'Ciências Biológicas', popular: false },
  { nome: 'Ciências Biomédicas', area: 'Ciências Biológicas', popular: false },
  { nome: 'Ecologia', area: 'Ciências Biológicas', popular: false },
  { nome: 'Ciências Naturais', area: 'Ciências Biológicas', popular: false },

  // ── Ciências Humanas / Licenciaturas ────────────────────────
  { nome: 'Pedagogia', area: 'Ciências Humanas', popular: true },
  { nome: 'Letras', area: 'Ciências Humanas', popular: true },
  { nome: 'Letras - Português', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Inglês', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Espanhol', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Português e Inglês', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Libras', area: 'Ciências Humanas', popular: false },
  { nome: 'História', area: 'Ciências Humanas', popular: true },
  { nome: 'Geografia', area: 'Ciências Humanas', popular: true },
  { nome: 'Filosofia', area: 'Ciências Humanas', popular: false },
  { nome: 'Sociologia', area: 'Ciências Humanas', popular: false },
  { nome: 'Ciências Sociais', area: 'Ciências Humanas', popular: false },
  { nome: 'Antropologia', area: 'Ciências Humanas', popular: false },
  { nome: 'Arqueologia', area: 'Ciências Humanas', popular: false },
  { nome: 'Ciências da Religião', area: 'Ciências Humanas', popular: false },
  { nome: 'Teologia', area: 'Ciências Humanas', popular: false },
  { nome: 'Ciência Política', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Tradutor e Intérprete', area: 'Ciências Humanas', popular: false },

  // ── Ciências Agrárias ───────────────────────────────────────
  { nome: 'Agronomia', area: 'Ciências Agrárias', popular: true },
  { nome: 'Zootecnia', area: 'Ciências Agrárias', popular: false },
  { nome: 'Agroecologia', area: 'Ciências Agrárias', popular: false },
  { nome: 'Ciências Agrárias', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Agronegócio', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Produção Agropecuária', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Cafeicultura', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Horticultura', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Irrigação e Drenagem', area: 'Ciências Agrárias', popular: false },

  // ── Tecnólogos ──────────────────────────────────────────────
  { nome: 'Tecnólogo em Análise e Desenvolvimento de Sistemas', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Gestão Comercial', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Logística', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Marketing', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Recursos Humanos', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Gestão Financeira', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Gastronomia', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Gestão Pública', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Processos Gerenciais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Comércio Exterior', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design Gráfico', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Interiores', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Moda', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Redes de Computadores', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Segurança da Informação', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Jogos Digitais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Multimídia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas para Internet', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Banco de Dados', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Ciência de Dados', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão da Tecnologia da Informação', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Estética e Cosmética', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Radiologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Eventos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Hotelaria', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Turismo', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Agronegócio', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Mecatrônica Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Automação Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Eletrônica Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Fabricação Mecânica', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Construção de Edifícios', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão da Produção Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Petróleo e Gás', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Saneamento Ambiental', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Energias Renováveis', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Hospitalar', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Negócios Imobiliários', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Audiovisual', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Comércio Eletrônico', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Marketing Digital', area: 'Tecnólogos', popular: true },
  { nome: 'Tecnólogo em Gestão da Qualidade', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Logística Empresarial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Secretariado', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Seguros', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Tributária', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Negócios Digitais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Cooperativas', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Análise de Dados', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Cênica', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Games', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Produto', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Animação', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Fotografia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Fonográfica', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Publicitária', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Conservação e Restauro', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Desportiva e de Lazer', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Segurança Privada', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Segurança no Trabalho', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Segurança Pública', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Cidades', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Investigação Forense e Perícia Criminal', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção de Bebidas', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Viticultura e Enologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Laticínios', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Alimentos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção de Alimentos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Agroindústria', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Aquicultura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Silvicultura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Ambiental', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Biocombustíveis', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Mineração', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Rochas Ornamentais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Materiais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Polímeros', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Processos Químicos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Processos Metalúrgicos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Soldagem', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Manutenção Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Manutenção de Aeronaves', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Pilotagem Profissional de Aeronaves', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas de Telecomunicações', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas Elétricos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas Eletrônicos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas Biomédicos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Eletrotécnica Industrial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Mecânica de Precisão', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Edificações', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Estradas', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Transporte Terrestre', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Logística Aeroportuária', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Portuária', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Big Data', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Inteligência Artificial', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Internet das Coisas', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Computação em Nuvem', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Defesa Cibernética', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Telemática', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Geoprocessamento', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Agrimensura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Estética e Imagem Pessoal', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Cosmetologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Óptica e Optometria', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gerontologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão da Saúde', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Serviços Jurídicos e Notariais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão Bancária', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Eventos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Comunicação Institucional', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Construção Civil', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Refrigeração e Climatização', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Recursos Hídricos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Energia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Eletrônica', area: 'Tecnólogos', popular: false },

  // ── Licenciaturas ───────────────────────────────────────────
  { nome: 'Licenciatura em Pedagogia', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Matemática', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Física', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Química', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Ciências Biológicas', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em História', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Geografia', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Letras - Português', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Letras - Inglês', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Letras - Espanhol', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Filosofia', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Sociologia', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Ciências Sociais', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Educação Física', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Artes Visuais', area: 'Comunicação e Artes', popular: false },
  { nome: 'Licenciatura em Música', area: 'Comunicação e Artes', popular: false },
  { nome: 'Licenciatura em Teatro', area: 'Comunicação e Artes', popular: false },
  { nome: 'Licenciatura em Dança', area: 'Comunicação e Artes', popular: false },
  { nome: 'Licenciatura em Computação', area: 'Computação e TI', popular: false },
  { nome: 'Licenciatura em Ciências da Natureza', area: 'Ciências Biológicas', popular: false },
  { nome: 'Licenciatura em Educação do Campo', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Ciências da Religião', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Letras-Libras', area: 'Ciências Humanas', popular: false },
  { nome: 'Licenciatura em Pedagogia Bilíngue', area: 'Ciências Humanas', popular: false },
  { nome: 'Educação Especial', area: 'Ciências Humanas', popular: false },

  // ── Engenharias (variantes) ─────────────────────────────────
  { nome: 'Engenharia Eletrotécnica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Sistemas', area: 'Engenharias', popular: false },
  { nome: 'Engenharia da Computação e Informação', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Ferroviária e Metroviária', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Mobilidade', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Geológica', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Industrial Madeireira', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Saúde e Segurança', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Hospitalar', area: 'Engenharias', popular: false },
  { nome: 'Engenharia da Sustentabilidade', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Gestão', area: 'Engenharias', popular: false },
  { nome: 'Engenharia Eletrônica e de Computação', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Automação', area: 'Engenharias', popular: false },
  { nome: 'Engenharia de Recursos Hídricos', area: 'Engenharias', popular: false },

  // ── Ciências da Saúde / Biológicas (variantes) ──────────────
  { nome: 'Acupuntura', area: 'Ciências da Saúde', popular: false },
  { nome: 'Cosmetologia e Estética', area: 'Ciências da Saúde', popular: false },
  { nome: 'Gestão em Saúde', area: 'Ciências da Saúde', popular: false },
  { nome: 'Bioquímica', area: 'Ciências Biológicas', popular: false },
  { nome: 'Biofísica', area: 'Ciências Biológicas', popular: false },
  { nome: 'Genética', area: 'Ciências Biológicas', popular: false },
  { nome: 'Microbiologia e Imunologia', area: 'Ciências Biológicas', popular: false },
  { nome: 'Ciências Moleculares', area: 'Ciências Biológicas', popular: false },
  { nome: 'Farmácia e Bioquímica', area: 'Ciências da Saúde', popular: false },

  // ── Letras / Humanas (variantes) ────────────────────────────
  { nome: 'Letras - Francês', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Alemão', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Italiano', area: 'Ciências Humanas', popular: false },
  { nome: 'Letras - Japonês', area: 'Ciências Humanas', popular: false },
  { nome: 'Tradução e Interpretação', area: 'Ciências Humanas', popular: false },
  { nome: 'Linguística', area: 'Ciências Humanas', popular: false },
  { nome: 'Estudos de Mídia', area: 'Ciências Humanas', popular: false },
  { nome: 'Humanidades', area: 'Ciências Humanas', popular: false },
  { nome: 'Gestão de Políticas Públicas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Defesa e Gestão Estratégica Internacional', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Economia', area: 'Ciências Sociais Aplicadas', popular: false },

  // ── Comunicação / Artes (variantes) ─────────────────────────
  { nome: 'Comunicação Organizacional', area: 'Comunicação e Artes', popular: false },
  { nome: 'Comunicação e Multimeios', area: 'Comunicação e Artes', popular: false },
  { nome: 'Artes Plásticas', area: 'Comunicação e Artes', popular: false },
  { nome: 'Gravura', area: 'Comunicação e Artes', popular: false },
  { nome: 'Pintura', area: 'Comunicação e Artes', popular: false },
  { nome: 'Escultura', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design de Interação', area: 'Comunicação e Artes', popular: false },
  { nome: 'Design Visual', area: 'Comunicação e Artes', popular: false },
  { nome: 'Paisagismo', area: 'Comunicação e Artes', popular: false },
  { nome: 'Urbanismo', area: 'Comunicação e Artes', popular: false },
  { nome: 'Editoração', area: 'Comunicação e Artes', popular: false },

  // ── Computação e TI (variantes) ─────────────────────────────
  { nome: 'Gestão da Informação', area: 'Computação e TI', popular: false },
  { nome: 'Engenharia da Informação', area: 'Computação e TI', popular: false },
  { nome: 'Sistemas de Computação', area: 'Computação e TI', popular: false },
  { nome: 'Tecnologia da Informação', area: 'Computação e TI', popular: false },
  { nome: 'Matemática Computacional', area: 'Computação e TI', popular: false },

  // ── Ciências Agrárias (variantes) ───────────────────────────
  { nome: 'Engenharia de Aquicultura', area: 'Ciências Agrárias', popular: false },
  { nome: 'Administração de Agronegócios', area: 'Ciências Agrárias', popular: false },
  { nome: 'Irrigação e Drenagem', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Alimentos', area: 'Ciências Agrárias', popular: false },
  { nome: 'Tecnologia em Laticínios', area: 'Ciências Agrárias', popular: false },

  // ── Negócios / Gestão (variantes) ───────────────────────────
  { nome: 'Administração de Empresas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Administração Hospitalar', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Negócios Internacionais', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Finanças', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão de Projetos', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão da Inovação', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão de Startups', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Educacional', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Gestão Esportiva', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Marketing e Vendas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Comércio', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Ciências Aeronáuticas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Ciências Náuticas', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Ciências Militares', area: 'Ciências Sociais Aplicadas', popular: false },
  { nome: 'Pilotagem de Aeronaves', area: 'Ciências Sociais Aplicadas', popular: false },

  // ── Tecnólogos (indústria e produção) ───────────────────────
  { nome: 'Tecnólogo em Gestão de Recursos Humanos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Negócios Internacionais', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Comércio', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Marketing e Propaganda', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Têxtil', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Design de Calçados', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Couro e Calçados', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Moveleira', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Sucroalcooleira', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção de Plásticos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Papel e Celulose', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Cerâmica', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Vidros', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Joalheria', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gemologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Controle Ambiental', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Gestão de Resíduos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Topografia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Geodésia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Hidrologia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Transporte Aéreo', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Manutenção de Sistemas Metroferroviários', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas Automotivos', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Manutenção Automotiva', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Mecânica Automobilística', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Eletromecânica', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Hidráulica e Saneamento', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Construção Naval', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Sistemas de Energia', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Apicultura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Fruticultura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Floricultura', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Pesqueira', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Hospitalidade', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Lazer e Qualidade de Vida', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Treinamento Desportivo', area: 'Tecnólogos', popular: false },
  { nome: 'Tecnólogo em Produção Cultural', area: 'Tecnólogos', popular: false },
]
