// Curated list of Brazilian higher-education institutions.
// Source: distilled from e-MEC / INEP records + common public variants.
// `popular: true` surfaces the institution at the top of the autocomplete.
// Matching (in AutocompleteInput) is case- and accent-insensitive and the
// onboarding accepts any free-typed value, so this list is a convenience —
// not an allow-list.

export const universidades = [
  // ── Universidades federais ──────────────────────────────────
  { nome: 'Universidade de São Paulo', sigla: 'USP', uf: 'SP', popular: true },
  { nome: 'Universidade Estadual de Campinas', sigla: 'Unicamp', uf: 'SP', popular: true },
  { nome: 'Universidade Estadual Paulista', sigla: 'UNESP', uf: 'SP', popular: true },
  { nome: 'Universidade Federal do Rio de Janeiro', sigla: 'UFRJ', uf: 'RJ', popular: true },
  { nome: 'Universidade Federal de Minas Gerais', sigla: 'UFMG', uf: 'MG', popular: true },
  { nome: 'Universidade Federal do Rio Grande do Sul', sigla: 'UFRGS', uf: 'RS', popular: true },
  { nome: 'Universidade Federal de Santa Catarina', sigla: 'UFSC', uf: 'SC', popular: true },
  { nome: 'Universidade Federal do Paraná', sigla: 'UFPR', uf: 'PR', popular: true },
  { nome: 'Universidade Federal da Bahia', sigla: 'UFBA', uf: 'BA', popular: true },
  { nome: 'Universidade Federal de Pernambuco', sigla: 'UFPE', uf: 'PE', popular: true },
  { nome: 'Universidade Federal do Ceará', sigla: 'UFC', uf: 'CE', popular: true },
  { nome: 'Universidade Federal Fluminense', sigla: 'UFF', uf: 'RJ', popular: true },
  { nome: 'Universidade Federal de São Carlos', sigla: 'UFSCar', uf: 'SP', popular: true },
  { nome: 'Universidade Federal do ABC', sigla: 'UFABC', uf: 'SP', popular: true },
  { nome: 'Universidade Federal de São Paulo', sigla: 'UNIFESP', uf: 'SP', popular: true },
  { nome: 'Universidade de Brasília', sigla: 'UnB', uf: 'DF', popular: true },
  { nome: 'Universidade Federal de Goiás', sigla: 'UFG', uf: 'GO', popular: true },
  { nome: 'Universidade Federal do Pará', sigla: 'UFPA', uf: 'PA', popular: true },
  { nome: 'Universidade Federal do Amazonas', sigla: 'UFAM', uf: 'AM', popular: true },
  { nome: 'Universidade Federal do Rio Grande do Norte', sigla: 'UFRN', uf: 'RN', popular: true },
  { nome: 'Universidade Federal da Paraíba', sigla: 'UFPB', uf: 'PB', popular: true },
  { nome: 'Universidade Federal do Espírito Santo', sigla: 'UFES', uf: 'ES', popular: true },
  { nome: 'Universidade Federal de Uberlândia', sigla: 'UFU', uf: 'MG', popular: true },
  { nome: 'Universidade Federal de Viçosa', sigla: 'UFV', uf: 'MG', popular: true },
  { nome: 'Universidade Federal de Juiz de Fora', sigla: 'UFJF', uf: 'MG', popular: true },
  { nome: 'Universidade Federal de Santa Maria', sigla: 'UFSM', uf: 'RS', popular: true },
  { nome: 'Universidade Federal de Pelotas', sigla: 'UFPel', uf: 'RS', popular: false },
  { nome: 'Universidade Federal de Mato Grosso', sigla: 'UFMT', uf: 'MT', popular: true },
  { nome: 'Universidade Federal de Mato Grosso do Sul', sigla: 'UFMS', uf: 'MS', popular: true },
  { nome: 'Universidade Federal de Alagoas', sigla: 'UFAL', uf: 'AL', popular: true },
  { nome: 'Universidade Federal de Sergipe', sigla: 'UFS', uf: 'SE', popular: true },
  { nome: 'Universidade Federal do Piauí', sigla: 'UFPI', uf: 'PI', popular: true },
  { nome: 'Universidade Federal do Maranhão', sigla: 'UFMA', uf: 'MA', popular: true },
  { nome: 'Universidade Federal de Lavras', sigla: 'UFLA', uf: 'MG', popular: true },
  { nome: 'Universidade Federal de Ouro Preto', sigla: 'UFOP', uf: 'MG', popular: true },
  { nome: 'Universidade Federal de Campina Grande', sigla: 'UFCG', uf: 'PB', popular: false },
  { nome: 'Universidade Federal Rural de Pernambuco', sigla: 'UFRPE', uf: 'PE', popular: false },
  { nome: 'Universidade Federal Rural do Rio de Janeiro', sigla: 'UFRRJ', uf: 'RJ', popular: false },
  { nome: 'Universidade Federal Rural da Amazônia', sigla: 'UFRA', uf: 'PA', popular: false },
  { nome: 'Universidade Federal Rural do Semi-Árido', sigla: 'UFERSA', uf: 'RN', popular: false },
  { nome: 'Universidade Federal de Roraima', sigla: 'UFRR', uf: 'RR', popular: false },
  { nome: 'Universidade Federal do Acre', sigla: 'UFAC', uf: 'AC', popular: false },
  { nome: 'Universidade Federal do Tocantins', sigla: 'UFT', uf: 'TO', popular: false },
  { nome: 'Universidade Federal de Rondônia', sigla: 'UNIR', uf: 'RO', popular: false },
  { nome: 'Universidade Federal do Amapá', sigla: 'UNIFAP', uf: 'AP', popular: false },
  { nome: 'Universidade Federal do Recôncavo da Bahia', sigla: 'UFRB', uf: 'BA', popular: false },
  { nome: 'Universidade Federal do Sul da Bahia', sigla: 'UFSB', uf: 'BA', popular: false },
  { nome: 'Universidade Federal do Oeste da Bahia', sigla: 'UFOB', uf: 'BA', popular: false },
  { nome: 'Universidade Federal do Vale do São Francisco', sigla: 'UNIVASF', uf: 'PE', popular: false },
  { nome: 'Universidade Federal dos Vales do Jequitinhonha e Mucuri', sigla: 'UFVJM', uf: 'MG', popular: false },
  { nome: 'Universidade Federal de São João del-Rei', sigla: 'UFSJ', uf: 'MG', popular: false },
  { nome: 'Universidade Federal de Itajubá', sigla: 'UNIFEI', uf: 'MG', popular: false },
  { nome: 'Universidade Federal de Alfenas', sigla: 'UNIFAL', uf: 'MG', popular: false },
  { nome: 'Universidade Federal do Triângulo Mineiro', sigla: 'UFTM', uf: 'MG', popular: false },
  { nome: 'Universidade Federal da Grande Dourados', sigla: 'UFGD', uf: 'MS', popular: false },
  { nome: 'Universidade Federal da Fronteira Sul', sigla: 'UFFS', uf: 'SC', popular: false },
  { nome: 'Universidade Federal do Pampa', sigla: 'UNIPAMPA', uf: 'RS', popular: false },
  { nome: 'Universidade Federal de Ciências da Saúde de Porto Alegre', sigla: 'UFCSPA', uf: 'RS', popular: false },
  { nome: 'Universidade Federal do Cariri', sigla: 'UFCA', uf: 'CE', popular: false },
  { nome: 'Universidade Federal do Oeste do Pará', sigla: 'UFOPA', uf: 'PA', popular: false },
  { nome: 'Universidade Federal do Sul e Sudeste do Pará', sigla: 'UNIFESSPA', uf: 'PA', popular: false },
  { nome: 'Universidade Federal do Delta do Parnaíba', sigla: 'UFDPar', uf: 'PI', popular: false },
  { nome: 'Universidade Federal do Norte do Tocantins', sigla: 'UFNT', uf: 'TO', popular: false },
  { nome: 'Universidade Federal do Agreste de Pernambuco', sigla: 'UFAPE', uf: 'PE', popular: false },
  { nome: 'Universidade Federal de Catalão', sigla: 'UFCAT', uf: 'GO', popular: false },
  { nome: 'Universidade Federal de Jataí', sigla: 'UFJ', uf: 'GO', popular: false },
  { nome: 'Universidade Federal de Rondonópolis', sigla: 'UFR', uf: 'MT', popular: false },
  { nome: 'Universidade da Integração Internacional da Lusofonia Afro-Brasileira', sigla: 'UNILAB', uf: 'CE', popular: false },
  { nome: 'Universidade Federal da Integração Latino-Americana', sigla: 'UNILA', uf: 'PR', popular: false },
  { nome: 'Universidade Tecnológica Federal do Paraná', sigla: 'UTFPR', uf: 'PR', popular: true },

  // ── Universidades estaduais ─────────────────────────────────
  { nome: 'Universidade do Estado do Rio de Janeiro', sigla: 'UERJ', uf: 'RJ', popular: true },
  { nome: 'Universidade Estadual de Maringá', sigla: 'UEM', uf: 'PR', popular: true },
  { nome: 'Universidade Estadual de Londrina', sigla: 'UEL', uf: 'PR', popular: true },
  { nome: 'Universidade Estadual de Ponta Grossa', sigla: 'UEPG', uf: 'PR', popular: false },
  { nome: 'Universidade Estadual do Oeste do Paraná', sigla: 'UNIOESTE', uf: 'PR', popular: false },
  { nome: 'Universidade Estadual do Centro-Oeste', sigla: 'UNICENTRO', uf: 'PR', popular: false },
  { nome: 'Universidade Estadual do Norte do Paraná', sigla: 'UENP', uf: 'PR', popular: false },
  { nome: 'Universidade Estadual de Feira de Santana', sigla: 'UEFS', uf: 'BA', popular: false },
  { nome: 'Universidade do Estado da Bahia', sigla: 'UNEB', uf: 'BA', popular: false },
  { nome: 'Universidade Estadual de Santa Cruz', sigla: 'UESC', uf: 'BA', popular: false },
  { nome: 'Universidade Estadual do Sudoeste da Bahia', sigla: 'UESB', uf: 'BA', popular: false },
  { nome: 'Universidade Estadual de Goiás', sigla: 'UEG', uf: 'GO', popular: false },
  { nome: 'Universidade do Estado de Minas Gerais', sigla: 'UEMG', uf: 'MG', popular: false },
  { nome: 'Universidade Estadual de Montes Claros', sigla: 'Unimontes', uf: 'MG', popular: false },
  { nome: 'Universidade do Estado de Mato Grosso', sigla: 'UNEMAT', uf: 'MT', popular: false },
  { nome: 'Universidade Estadual de Mato Grosso do Sul', sigla: 'UEMS', uf: 'MS', popular: false },
  { nome: 'Universidade Estadual do Ceará', sigla: 'UECE', uf: 'CE', popular: false },
  { nome: 'Universidade Regional do Cariri', sigla: 'URCA', uf: 'CE', popular: false },
  { nome: 'Universidade Estadual do Maranhão', sigla: 'UEMA', uf: 'MA', popular: false },
  { nome: 'Universidade Estadual do Piauí', sigla: 'UESPI', uf: 'PI', popular: false },
  { nome: 'Universidade Estadual da Paraíba', sigla: 'UEPB', uf: 'PB', popular: false },
  { nome: 'Universidade de Pernambuco', sigla: 'UPE', uf: 'PE', popular: false },
  { nome: 'Universidade do Estado do Rio Grande do Norte', sigla: 'UERN', uf: 'RN', popular: false },
  { nome: 'Universidade do Estado do Pará', sigla: 'UEPA', uf: 'PA', popular: false },
  { nome: 'Universidade do Estado do Amazonas', sigla: 'UEA', uf: 'AM', popular: false },
  { nome: 'Universidade do Estado de Mato Grosso', sigla: 'UNEMAT-MT', uf: 'MT', popular: false },
  { nome: 'Universidade Estadual do Rio Grande do Sul', sigla: 'UERGS', uf: 'RS', popular: false },
  { nome: 'Universidade Estadual de Santa Catarina', sigla: 'UDESC', uf: 'SC', popular: false },
  { nome: 'Universidade do Estado do Amapá', sigla: 'UEAP', uf: 'AP', popular: false },
  { nome: 'Universidade Virtual do Estado de São Paulo', sigla: 'UNIVESP', uf: 'SP', popular: false },

  // ── Institutos federais e CEFETs ────────────────────────────
  { nome: 'Instituto Federal de São Paulo', sigla: 'IFSP', uf: 'SP', popular: true },
  { nome: 'Instituto Federal do Rio de Janeiro', sigla: 'IFRJ', uf: 'RJ', popular: false },
  { nome: 'Instituto Federal de Minas Gerais', sigla: 'IFMG', uf: 'MG', popular: false },
  { nome: 'Instituto Federal do Rio Grande do Sul', sigla: 'IFRS', uf: 'RS', popular: false },
  { nome: 'Instituto Federal de Santa Catarina', sigla: 'IFSC', uf: 'SC', popular: false },
  { nome: 'Instituto Federal do Paraná', sigla: 'IFPR', uf: 'PR', popular: false },
  { nome: 'Instituto Federal da Bahia', sigla: 'IFBA', uf: 'BA', popular: false },
  { nome: 'Instituto Federal de Pernambuco', sigla: 'IFPE', uf: 'PE', popular: false },
  { nome: 'Instituto Federal do Ceará', sigla: 'IFCE', uf: 'CE', popular: false },
  { nome: 'Instituto Federal de Goiás', sigla: 'IFG', uf: 'GO', popular: false },
  { nome: 'Instituto Federal de Brasília', sigla: 'IFB', uf: 'DF', popular: false },
  { nome: 'Instituto Federal do Espírito Santo', sigla: 'IFES', uf: 'ES', popular: false },
  { nome: 'Instituto Federal do Norte de Minas Gerais', sigla: 'IFNMG', uf: 'MG', popular: false },
  { nome: 'Instituto Federal do Sul de Minas Gerais', sigla: 'IFSULDEMINAS', uf: 'MG', popular: false },
  { nome: 'Instituto Federal do Triângulo Mineiro', sigla: 'IFTM', uf: 'MG', popular: false },
  { nome: 'Instituto Federal Fluminense', sigla: 'IFF', uf: 'RJ', popular: false },
  { nome: 'Instituto Federal Sul-rio-grandense', sigla: 'IFSul', uf: 'RS', popular: false },
  { nome: 'Instituto Federal Farroupilha', sigla: 'IFFar', uf: 'RS', popular: false },
  { nome: 'Instituto Federal do Amazonas', sigla: 'IFAM', uf: 'AM', popular: false },
  { nome: 'Instituto Federal do Pará', sigla: 'IFPA', uf: 'PA', popular: false },
  { nome: 'Instituto Federal do Maranhão', sigla: 'IFMA', uf: 'MA', popular: false },
  { nome: 'Instituto Federal do Piauí', sigla: 'IFPI', uf: 'PI', popular: false },
  { nome: 'Instituto Federal da Paraíba', sigla: 'IFPB', uf: 'PB', popular: false },
  { nome: 'Instituto Federal do Rio Grande do Norte', sigla: 'IFRN', uf: 'RN', popular: false },
  { nome: 'Instituto Federal de Alagoas', sigla: 'IFAL', uf: 'AL', popular: false },
  { nome: 'Instituto Federal de Sergipe', sigla: 'IFS', uf: 'SE', popular: false },
  { nome: 'Instituto Federal de Mato Grosso', sigla: 'IFMT', uf: 'MT', popular: false },
  { nome: 'Instituto Federal de Mato Grosso do Sul', sigla: 'IFMS', uf: 'MS', popular: false },
  { nome: 'Instituto Federal do Tocantins', sigla: 'IFTO', uf: 'TO', popular: false },
  { nome: 'Instituto Federal de Rondônia', sigla: 'IFRO', uf: 'RO', popular: false },
  { nome: 'Instituto Federal do Acre', sigla: 'IFAC', uf: 'AC', popular: false },
  { nome: 'Instituto Federal de Roraima', sigla: 'IFRR', uf: 'RR', popular: false },
  { nome: 'Instituto Federal do Amapá', sigla: 'IFAP', uf: 'AP', popular: false },
  { nome: 'Instituto Federal do Sertão Pernambucano', sigla: 'IFSertãoPE', uf: 'PE', popular: false },
  { nome: 'Instituto Federal Baiano', sigla: 'IFBaiano', uf: 'BA', popular: false },
  { nome: 'Instituto Federal Goiano', sigla: 'IFGoiano', uf: 'GO', popular: false },
  { nome: 'Instituto Federal Catarinense', sigla: 'IFC', uf: 'SC', popular: false },
  { nome: 'Centro Federal de Educação Tecnológica de Minas Gerais', sigla: 'CEFET-MG', uf: 'MG', popular: false },
  { nome: 'Centro Federal de Educação Tecnológica Celso Suckow da Fonseca', sigla: 'CEFET-RJ', uf: 'RJ', popular: false },

  // ── Militares e institutos de pesquisa ──────────────────────
  { nome: 'Instituto Tecnológico de Aeronáutica', sigla: 'ITA', uf: 'SP', popular: true },
  { nome: 'Instituto Militar de Engenharia', sigla: 'IME', uf: 'RJ', popular: true },
  { nome: 'Academia Militar das Agulhas Negras', sigla: 'AMAN', uf: 'RJ', popular: false },
  { nome: 'Escola Naval', sigla: 'EN', uf: 'RJ', popular: false },
  { nome: 'Academia da Força Aérea', sigla: 'AFA', uf: 'SP', popular: false },
  { nome: 'Escola de Comando e Estado-Maior do Exército', sigla: 'ECEME', uf: 'RJ', popular: false },
  { nome: 'Fundação Oswaldo Cruz', sigla: 'Fiocruz', uf: 'RJ', popular: false },
  { nome: 'Empresa Brasileira de Pesquisa Agropecuária', sigla: 'Embrapa', uf: 'DF', popular: false },
  { nome: 'Escola Superior de Agricultura Luiz de Queiroz', sigla: 'ESALQ', uf: 'SP', popular: false },

  // ── Confessionais / PUCs ────────────────────────────────────
  { nome: 'Pontifícia Universidade Católica de São Paulo', sigla: 'PUC-SP', uf: 'SP', popular: true },
  { nome: 'Pontifícia Universidade Católica do Rio de Janeiro', sigla: 'PUC-Rio', uf: 'RJ', popular: true },
  { nome: 'Pontifícia Universidade Católica de Minas Gerais', sigla: 'PUC Minas', uf: 'MG', popular: true },
  { nome: 'Pontifícia Universidade Católica do Rio Grande do Sul', sigla: 'PUCRS', uf: 'RS', popular: true },
  { nome: 'Pontifícia Universidade Católica do Paraná', sigla: 'PUCPR', uf: 'PR', popular: true },
  { nome: 'Pontifícia Universidade Católica de Campinas', sigla: 'PUC-Campinas', uf: 'SP', popular: true },
  { nome: 'Pontifícia Universidade Católica de Goiás', sigla: 'PUC Goiás', uf: 'GO', popular: false },
  { nome: 'Universidade Católica de Brasília', sigla: 'UCB', uf: 'DF', popular: false },
  { nome: 'Universidade Católica de Pernambuco', sigla: 'Unicap', uf: 'PE', popular: false },
  { nome: 'Universidade Católica do Salvador', sigla: 'UCSal', uf: 'BA', popular: false },
  { nome: 'Universidade Católica de Pelotas', sigla: 'UCPel', uf: 'RS', popular: false },
  { nome: 'Universidade Católica de Santos', sigla: 'UniSantos', uf: 'SP', popular: false },
  { nome: 'Universidade do Vale do Rio dos Sinos', sigla: 'Unisinos', uf: 'RS', popular: false },
  { nome: 'Universidade Presbiteriana Mackenzie', sigla: 'Mackenzie', uf: 'SP', popular: true },
  { nome: 'Universidade Metodista de São Paulo', sigla: 'Metodista', uf: 'SP', popular: false },
  { nome: 'Universidade Metodista de Piracicaba', sigla: 'Unimep', uf: 'SP', popular: false },
  { nome: 'Universidade São Francisco', sigla: 'USF', uf: 'SP', popular: false },

  // ── Negócios / elite privada ────────────────────────────────
  { nome: 'Fundação Getulio Vargas', sigla: 'FGV', uf: 'SP', popular: true },
  { nome: 'Fundação Getulio Vargas (Rio de Janeiro)', sigla: 'FGV-RJ', uf: 'RJ', popular: true },
  { nome: 'Escola Superior de Propaganda e Marketing', sigla: 'ESPM', uf: 'SP', popular: true },
  { nome: 'Escola Superior de Propaganda e Marketing (Rio de Janeiro)', sigla: 'ESPM-RJ', uf: 'RJ', popular: false },
  { nome: 'Escola Superior de Propaganda e Marketing (Sul)', sigla: 'ESPM-Sul', uf: 'RS', popular: false },
  { nome: 'Insper Instituto de Ensino e Pesquisa', sigla: 'Insper', uf: 'SP', popular: true },
  { nome: 'Instituto Brasileiro de Mercado de Capitais', sigla: 'IBMEC', uf: 'SP', popular: true },
  { nome: 'IBMEC Rio de Janeiro', sigla: 'IBMEC-RJ', uf: 'RJ', popular: false },
  { nome: 'IBMEC Belo Horizonte', sigla: 'IBMEC-BH', uf: 'MG', popular: false },
  { nome: 'IBMEC Brasília', sigla: 'IBMEC-DF', uf: 'DF', popular: false },
  { nome: 'Fundação Armando Alvares Penteado', sigla: 'FAAP', uf: 'SP', popular: true },
  { nome: 'Centro Universitário FEI', sigla: 'FEI', uf: 'SP', popular: true },
  { nome: 'Instituto Mauá de Tecnologia', sigla: 'Mauá', uf: 'SP', popular: true },
  { nome: 'Faculdade de Campinas', sigla: 'FACAMP', uf: 'SP', popular: false },
  { nome: 'Fundação Dom Cabral', sigla: 'FDC', uf: 'MG', popular: false },
  { nome: 'Saint Paul Escola de Negócios', sigla: 'Saint Paul', uf: 'SP', popular: false },
  { nome: 'Trevisan Escola de Negócios', sigla: 'Trevisan', uf: 'SP', popular: false },
  { nome: 'Faculdade de Comunicação Social Cásper Líbero', sigla: 'Cásper Líbero', uf: 'SP', popular: true },
  { nome: 'Centro Universitário Belas Artes de São Paulo', sigla: 'Belas Artes', uf: 'SP', popular: false },
  { nome: 'Escola Brasileira de Economia e Finanças', sigla: 'EBEF', uf: 'RJ', popular: false },

  // ── Saúde específicas ───────────────────────────────────────
  { nome: 'Faculdade de Ciências Médicas da Santa Casa de São Paulo', sigla: 'FCMSCSP', uf: 'SP', popular: true },
  { nome: 'Faculdade da Saúde e Ecologia Humana / Santa Casa de Belo Horizonte', sigla: 'Santa Casa BH', uf: 'MG', popular: false },
  { nome: 'Faculdade Santa Casa de Porto Alegre', sigla: 'Santa Casa POA', uf: 'RS', popular: false },
  { nome: 'Faculdade Israelita de Ciências da Saúde Albert Einstein', sigla: 'Einstein', uf: 'SP', popular: true },
  { nome: 'Instituto de Ensino e Pesquisa Sírio-Libanês', sigla: 'Sírio-Libanês', uf: 'SP', popular: true },
  { nome: 'Centro Universitário São Camilo', sigla: 'São Camilo', uf: 'SP', popular: true },
  { nome: 'Faculdade de Medicina do ABC', sigla: 'FMABC', uf: 'SP', popular: false },
  { nome: 'Faculdade de Medicina de Jundiaí', sigla: 'FMJ', uf: 'SP', popular: false },
  { nome: 'Faculdade de Medicina de São José do Rio Preto', sigla: 'FAMERP', uf: 'SP', popular: false },
  { nome: 'Faculdade de Medicina de Marília', sigla: 'Famema', uf: 'SP', popular: false },
  { nome: 'Escola Paulista de Medicina', sigla: 'EPM', uf: 'SP', popular: false },
  { nome: 'Escola Bahiana de Medicina e Saúde Pública', sigla: 'EBMSP', uf: 'BA', popular: false },
  { nome: 'Faculdade Pernambucana de Saúde', sigla: 'FPS', uf: 'PE', popular: false },

  // ── Grandes redes privadas ──────────────────────────────────
  { nome: 'Universidade Estácio de Sá', sigla: 'Estácio', uf: 'RJ', popular: true },
  { nome: 'Universidade Anhanguera', sigla: 'Anhanguera', uf: 'SP', popular: true },
  { nome: 'Universidade Paulista', sigla: 'UNIP', uf: 'SP', popular: true },
  { nome: 'Universidade Nove de Julho', sigla: 'UNINOVE', uf: 'SP', popular: true },
  { nome: 'Centro Universitário Leonardo da Vinci', sigla: 'Uniasselvi', uf: 'SC', popular: true },
  { nome: 'Universidade Cruzeiro do Sul', sigla: 'Cruzeiro do Sul', uf: 'SP', popular: true },
  { nome: 'Universidade Anhembi Morumbi', sigla: 'Anhembi Morumbi', uf: 'SP', popular: true },
  { nome: 'Universidade São Judas Tadeu', sigla: 'USJT', uf: 'SP', popular: true },
  { nome: 'Universidade Cidade de São Paulo', sigla: 'UNICID', uf: 'SP', popular: false },
  { nome: 'Universidade de Mogi das Cruzes', sigla: 'UMC', uf: 'SP', popular: false },
  { nome: 'Universidade São Marcos', sigla: 'USM', uf: 'SP', popular: false },
  { nome: 'Centro Universitário Senac', sigla: 'Senac', uf: 'SP', popular: true },
  { nome: 'Faculdade SENAI', sigla: 'SENAI', uf: 'SP', popular: false },
  { nome: 'Centro Universitário de Brasília', sigla: 'CEUB', uf: 'DF', popular: true },
  { nome: 'Centro Universitário Internacional', sigla: 'Uninter', uf: 'PR', popular: true },
  { nome: 'Universidade Pitágoras Unopar', sigla: 'Unopar', uf: 'PR', popular: true },
  { nome: 'Faculdade Descomplica', sigla: 'Descomplica', uf: 'RJ', popular: false },
  { nome: 'Faculdade UNIFTEC', sigla: 'UNIFTEC', uf: 'RS', popular: false },
  { nome: 'Centro Universitário FMU', sigla: 'FMU', uf: 'SP', popular: true },
  { nome: 'Universidade Ibirapuera', sigla: 'Unib', uf: 'SP', popular: false },
  { nome: 'Centro Universitário das Faculdades Metropolitanas Unidas', sigla: 'FMU-FIAM', uf: 'SP', popular: false },
  { nome: 'Universidade Tiradentes', sigla: 'Unit', uf: 'SE', popular: false },
  { nome: 'Universidade Salvador', sigla: 'UNIFACS', uf: 'BA', popular: false },
  { nome: 'Universidade Potiguar', sigla: 'UnP', uf: 'RN', popular: false },
  { nome: 'Centro Universitário Ritter dos Reis', sigla: 'UniRitter', uf: 'RS', popular: false },
  { nome: 'Universidade do Sul de Santa Catarina', sigla: 'Unisul', uf: 'SC', popular: false },
  { nome: 'Universidade do Vale do Itajaí', sigla: 'Univali', uf: 'SC', popular: false },
  { nome: 'Universidade da Região de Joinville', sigla: 'Univille', uf: 'SC', popular: false },
  { nome: 'Universidade de Caxias do Sul', sigla: 'UCS', uf: 'RS', popular: false },
  { nome: 'Universidade de Passo Fundo', sigla: 'UPF', uf: 'RS', popular: false },
  { nome: 'Universidade de Santa Cruz do Sul', sigla: 'Unisc', uf: 'RS', popular: false },
  { nome: 'Universidade Feevale', sigla: 'Feevale', uf: 'RS', popular: false },
  { nome: 'Universidade Positivo', sigla: 'UP', uf: 'PR', popular: false },
  { nome: 'Pontifícia Universidade Católica do Paraná (Curitiba)', sigla: 'PUCPR-Cur', uf: 'PR', popular: false },
  { nome: 'Universidade Regional de Blumenau', sigla: 'FURB', uf: 'SC', popular: false },
  { nome: 'Universidade de Fortaleza', sigla: 'Unifor', uf: 'CE', popular: true },
  { nome: 'Universidade Vila Velha', sigla: 'UVV', uf: 'ES', popular: false },
  { nome: 'Universidade de Marília', sigla: 'Unimar', uf: 'SP', popular: false },
  { nome: 'Universidade de Ribeirão Preto', sigla: 'Unaerp', uf: 'SP', popular: false },
  { nome: 'Universidade de Franca', sigla: 'Unifran', uf: 'SP', popular: false },
  { nome: 'Universidade do Oeste Paulista', sigla: 'Unoeste', uf: 'SP', popular: false },
  { nome: 'Universidade de Sorocaba', sigla: 'Uniso', uf: 'SP', popular: false },
  { nome: 'Universidade de Taubaté', sigla: 'Unitau', uf: 'SP', popular: false },
  { nome: 'Universidade de Mogi das Cruzes (Villa Lobos)', sigla: 'UMC-VL', uf: 'SP', popular: false },
  { nome: 'Universidade Braz Cubas', sigla: 'Braz Cubas', uf: 'SP', popular: false },
  { nome: 'Universidade Santa Cecília', sigla: 'Unisanta', uf: 'SP', popular: false },
  { nome: 'Universidade Metropolitana de Santos', sigla: 'Unimes', uf: 'SP', popular: false },
  { nome: 'Universidade Guarulhos', sigla: 'UnG', uf: 'SP', popular: false },
  { nome: 'Centro Universitário FIEO', sigla: 'UNIFIEO', uf: 'SP', popular: false },
  { nome: 'Centro Universitário Salesiano de São Paulo', sigla: 'UNISAL', uf: 'SP', popular: false },
  { nome: 'Centro Universitário da FEI (São Bernardo)', sigla: 'FEI-SBC', uf: 'SP', popular: false },
  { nome: 'Centro Universitário Adventista de São Paulo', sigla: 'UNASP', uf: 'SP', popular: false },
  { nome: 'Centro Universitário Fundação Santo André', sigla: 'FSA', uf: 'SP', popular: false },
  { nome: 'Centro Universitário FACENS', sigla: 'FACENS', uf: 'SP', popular: false },
  { nome: 'Centro Universitário do Instituto Mauá', sigla: 'CEUN-IMT', uf: 'SP', popular: false },
  { nome: 'Centro Universitário SENAI', sigla: 'SENAI-CIMATEC', uf: 'BA', popular: false },
  { nome: 'Faculdade Antonio Meneghetti', sigla: 'AMF', uf: 'RS', popular: false },
  { nome: 'Faculdade IBMR', sigla: 'IBMR', uf: 'RJ', popular: false },
  { nome: 'Faculdades Integradas Hélio Alonso', sigla: 'FACHA', uf: 'RJ', popular: false },
  { nome: 'Faculdade CESUSC', sigla: 'CESUSC', uf: 'SC', popular: false },
  { nome: 'Universidade Veiga de Almeida', sigla: 'UVA', uf: 'RJ', popular: false },
  { nome: 'Universidade Cândido Mendes', sigla: 'UCAM', uf: 'RJ', popular: false },
  { nome: 'Universidade do Grande Rio', sigla: 'Unigranrio', uf: 'RJ', popular: false },
  { nome: 'Universidade Salgado de Oliveira', sigla: 'Universo', uf: 'RJ', popular: false },
  { nome: 'Universidade Iguaçu', sigla: 'UNIG', uf: 'RJ', popular: false },
  { nome: 'Universidade do Sul de Minas', sigla: 'UNIS-MG', uf: 'MG', popular: false },
  { nome: 'Universidade Vale do Rio Doce', sigla: 'Univale', uf: 'MG', popular: false },
  { nome: 'Universidade José do Rosário Vellano', sigla: 'Unifenas', uf: 'MG', popular: false },
  { nome: 'Universidade de Itaúna', sigla: 'UIT', uf: 'MG', popular: false },
  { nome: 'Universidade FUMEC', sigla: 'FUMEC', uf: 'MG', popular: false },
  { nome: 'Centro Universitário de Belo Horizonte', sigla: 'UniBH', uf: 'MG', popular: false },
  { nome: 'Centro Universitário Newton Paiva', sigla: 'Newton Paiva', uf: 'MG', popular: false },
  { nome: 'Centro Universitário UNA', sigla: 'UNA', uf: 'MG', popular: false },
  { nome: 'Centro Universitário de Patos de Minas', sigla: 'UNIPAM', uf: 'MG', popular: false },
  { nome: 'Universidade de Uberaba', sigla: 'Uniube', uf: 'MG', popular: false },
  { nome: 'Universidade do Estado da Bahia (Salvador)', sigla: 'UNEB-SSA', uf: 'BA', popular: false },
  { nome: 'Faculdade Ruy Barbosa', sigla: 'Wyden', uf: 'BA', popular: false },
  { nome: 'Centro Universitário Jorge Amado', sigla: 'UNIJORGE', uf: 'BA', popular: false },
  { nome: 'Centro Universitário Estácio do Ceará', sigla: 'Estácio-CE', uf: 'CE', popular: false },
  { nome: 'Centro Universitário Christus', sigla: 'Unichristus', uf: 'CE', popular: false },
  { nome: 'Centro Universitário 7 de Setembro', sigla: 'UNI7', uf: 'CE', popular: false },
  { nome: 'Faculdade Farias Brito', sigla: 'FFB', uf: 'CE', popular: false },
  { nome: 'Universidade Católica de Goiás', sigla: 'PUC-GO', uf: 'GO', popular: false },
  { nome: 'Centro Universitário de Goiás', sigla: 'Uni-Anhanguera', uf: 'GO', popular: false },
  { nome: 'Universidade Evangélica de Goiás', sigla: 'UniEVANGÉLICA', uf: 'GO', popular: false },
  { nome: 'Centro Universitário de Brasília (CEUB)', sigla: 'UniCEUB', uf: 'DF', popular: false },
  { nome: 'Instituto Brasileiro de Ensino, Desenvolvimento e Pesquisa', sigla: 'IDP', uf: 'DF', popular: false },
  { nome: 'Centro Universitário do Distrito Federal', sigla: 'UDF', uf: 'DF', popular: false },
  { nome: 'Universidade Católica Dom Bosco', sigla: 'UCDB', uf: 'MS', popular: false },
  { nome: 'Universidade para o Desenvolvimento do Estado e da Região do Pantanal', sigla: 'Uniderp', uf: 'MS', popular: false },
  { nome: 'Universidade de Cuiabá', sigla: 'Unic', uf: 'MT', popular: false },
  { nome: 'Universidade da Amazônia', sigla: 'Unama', uf: 'PA', popular: false },
  { nome: 'Centro Universitário do Pará', sigla: 'CESUPA', uf: 'PA', popular: false },
  { nome: 'Universidade Nilton Lins', sigla: 'Nilton Lins', uf: 'AM', popular: false },
  { nome: 'Centro Universitário do Norte', sigla: 'UNINORTE', uf: 'AM', popular: false },
  { nome: 'Universidade Norte do Paraná', sigla: 'Unopar-PR', uf: 'PR', popular: false },
  { nome: 'Pontifícia Universidade Católica do Paraná (Londrina)', sigla: 'PUCPR-Lon', uf: 'PR', popular: false },
  { nome: 'Faculdade de Tecnologia do Estado de São Paulo', sigla: 'Fatec', uf: 'SP', popular: true },
  { nome: 'Fatec São Paulo', sigla: 'Fatec-SP', uf: 'SP', popular: false },
  { nome: 'Fatec Sorocaba', sigla: 'Fatec-Sorocaba', uf: 'SP', popular: false },
  { nome: 'Fatec Santo André', sigla: 'Fatec-SA', uf: 'SP', popular: false },
  { nome: 'Fatec Campinas', sigla: 'Fatec-Campinas', uf: 'SP', popular: false },
  { nome: 'Etec - Escola Técnica Estadual', sigla: 'Etec', uf: 'SP', popular: false },
  { nome: 'Centro Paula Souza', sigla: 'CPS', uf: 'SP', popular: false },
]
